
## User register request
#POST http://localhost:8080/api/v1/users/customer/register
#Content-Type: application/json
#
#{
#  "username": "testuser",
#  "password": "password123",
#  "phoneNumber": "13800138000"
#}

### User login request
POST http://localhost:8080/api/v1/users/customer/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}